name: Build and Upload Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      # Step1: Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python and Poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      # Step 3: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install --with docs

      # Step 4: Build the Sphinx documentation
      - name: Build the documentation
        run: |
          cd docs
          poetry run make html

      - name: Resolve symlinks and hard links in docs/build/html
        run: |
          cp -rL docs/build/html /tmp/resolved_html
          rm -rf docs/build/html/*
          mv /tmp/resolved_html/* docs/build/html/

      - name: Ensure no symlinks in build
        run: |
          find docs/build/html -type l -exec rm -f {} +

      - name: Check artifact size
        run: |
          du -sh docs/build/html

      # Step 5: Upload the built documentation as an artifact
      - name: Upload Sphinx documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/build/html

  deploy:
    # Add a dependency to the build job
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
